### ISSUE TITLE
BUG on 4.7 and 5.5 inch screen iphone

### ISSUE THREAD

**Issue by umxyz** [n3d1117/n3d1117.github.io#6]
![image](https://user-images.githubusercontent.com/44895726/83354090-7e1e8d80-a389-11ea-8fcd-e0d75f93ee31.png)
it seems like its position is shifted down a few pixels

**Comment by umxyz** [comment]
U can see this photo in black background
because the status bar is white
and in github reply it cannot show u

**Comment by TiboChristin** [comment]
Yeah, same for me : all colorized bar in status bar (red recording bar or green call bar) are wider than expected and exceeds the normal status bar size.

![image3](https://user-images.githubusercontent.com/14138009/84604639-b5b42c00-ae97-11ea-8a9d-a8f3533931c6.jpeg)

**Comment by umxyz** [comment]
> Yeah, same for me : all colorized bar in status bar (red recording bar or green call bar) are wider than expected and exceeds the normal status bar size.
> 
> ![image3](https://user-images.githubusercontent.com/14138009/84604639-b5b42c00-ae97-11ea-8a9d-a8f3533931c6.jpeg)

it's a nice tweak,But did not consider the old model

**Comment by SarahH12099** [comment]
This issue has been fixed in the upcoming 0.0.5 update, I have asked for this to be closed now
